name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.0, 8.1, 8.2 ]
    steps:
      - name: "Init repository"
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install Dependencies
        run: composer install

      - name: Audit Dependencies
        run: composer audit

      - name: Run PHPStan
        run: composer phpstan

      - name: Run tests
        run: composer test
